/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.lemma.technology.ui;

import com.google.inject.Injector;
import de.fhdo.lemma.technology.technologydsl.ui.internal.TechnologydslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TechnologyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TechnologydslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TechnologydslActivator activator = TechnologydslActivator.getInstance();
		return activator != null ? activator.getInjector(TechnologydslActivator.DE_FHDO_LEMMA_TECHNOLOGY_TECHNOLOGYDSL) : null;
	}

}
