/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.data.tests

import com.google.inject.Inject
import de.fhdo.ddmm.data.Version
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DataDslInjectorProvider)
class DataDslParsingTest {
	@Inject
	ParseHelper<Version> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
