/*
 * generated by Xtext 2.32.0
 */
package de.fhdo.lemma.scoping;

import de.fhdo.lemma.technology.scoping.TechnologyDslScopeProvider;

public abstract class AbstractServiceDslScopeProvider extends TechnologyDslScopeProvider {
}
