/*
 * generated by Xtext 2.25.0
 */
package de.fhdo.lemma.technology.scoping;

import de.fhdo.lemma.data.scoping.DataDslScopeProvider;

public abstract class AbstractTechnologyDslScopeProvider extends DataDslScopeProvider {
}
