/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.data;

import de.fhdo.ddmm.data.DataDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataDslStandaloneSetup extends DataDslStandaloneSetupGenerated {
  public static void doSetup() {
    new DataDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
