/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.lemma.operationdsl;

import com.google.inject.Injector;
import de.fhdo.lemma.operation.OperationPackage;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OperationDslStandaloneSetup extends OperationDslStandaloneSetupGenerated {
  public static void doSetup() {
    new OperationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  /**
   * NOTE: This overwritten method is necessary in order to register stuff like "DataModel" etc. for the language server correctly. See
   * https://www.eclipse.org/forums/index.php/t/1077902/
   */
  @Override
  public void register(final Injector injector) {
    EPackage.Registry.INSTANCE.put(OperationPackage.eINSTANCE.getNsURI(), OperationPackage.eINSTANCE);
    super.register(injector);
  }
}
