/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.lemma.operationdsl;

import de.fhdo.lemma.operationdsl.OperationDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OperationDslStandaloneSetup extends OperationDslStandaloneSetupGenerated {
  public static void doSetup() {
    new OperationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
