/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.operationdsl.ide


/**
 * Use this class to register ide components.
 */
class OperationDslIdeModule extends AbstractOperationDslIdeModule {
}
