/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.technology

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TechnologyDslRuntimeModule extends AbstractTechnologyDslRuntimeModule {
}
