/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.technology.ui.tests;

import com.google.inject.Injector;
import de.fhdo.ddmm.technology.technologydsl.ui.internal.TechnologydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TechnologyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TechnologydslActivator.getInstance().getInjector("de.fhdo.ddmm.technology.TechnologyDsl");
	}

}
