/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.data.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataDslScopeProvider extends DelegatingScopeProvider {
}
