/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.tests;

import com.google.inject.Inject;
import de.fhdo.ddmm.service.ServiceModel;
import de.fhdo.ddmm.tests.ServiceDslInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ServiceDslInjectorProvider.class)
@SuppressWarnings("all")
public class ServiceDslParsingTest {
  @Inject
  private ParseHelper<ServiceModel> parseHelper;
  
  @Test
  public void loadModel() {
  }
}
