/*
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.data


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DataDslStandaloneSetup extends DataDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DataDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
