/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.lemma.data.tests;

import com.google.inject.Inject;
import de.fhdo.lemma.data.DataModel;
import de.fhdo.lemma.data.tests.DataDslInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DataDslInjectorProvider.class)
@SuppressWarnings("all")
public class DataDslParsingTest {
  @Inject
  private ParseHelper<DataModel> parseHelper;
  
  @Test
  public void loadModel() {
  }
}
