/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.ddmm.technology.ui.contentassist;

import de.fhdo.ddmm.technology.ui.contentassist.AbstractTechnologyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TechnologyDslProposalProvider extends AbstractTechnologyDslProposalProvider {
}
