/**
 * generated by Xtext 2.12.0
 */
package de.fhdo.lemma.technology;

import de.fhdo.lemma.technology.AbstractTechnologyDslRuntimeModule;
import de.fhdo.lemma.technology.TechnologyDslResourceDescriptionStrategy;
import de.fhdo.lemma.technology.validation.TechnologyDslNamesAreUniqueValidationHelper;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.validation.INamesAreUniqueValidationHelper;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 * 
 * @author <a href="mailto:florian.rademacher@fh-dortmund.de">Florian Rademacher</a>
 */
@SuppressWarnings("all")
public class TechnologyDslRuntimeModule extends AbstractTechnologyDslRuntimeModule {
  public Class<? extends INamesAreUniqueValidationHelper> bindINamesAreUniqueValidationHelper() {
    return TechnologyDslNamesAreUniqueValidationHelper.class;
  }
  
  /**
   * Bind custom resource description strategy
   */
  public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
    return TechnologyDslResourceDescriptionStrategy.class;
  }
}
