/*
 * generated by Xtext 2.25.0
 */
package de.fhdo.lemma.data.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataDslScopeProvider extends DelegatingScopeProvider {
}
